/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "TaquitoAudioProcessorEditor.h"


//==============================================================================
TaquitoAudioProcessor::TaquitoAudioProcessor()
{
  breath = 0.5;
  position = 0.5;
  pressure = 0.5;

  lastUIWidth = 400;
  lastUIHeight = 200;

  startTimer (50);

  breathThreshold = 0.1;
  pressureThreshold = 0.1;
  channel = 1;
  octave = 4;
  breathController = 7;
  pressureController = 1;
  positionController = -1;
  memset(ccvalues, 0, sizeof(ccvalues));
  lastnote = -1;

}

TaquitoAudioProcessor::~TaquitoAudioProcessor()
{
}

//==============================================================================
int TaquitoAudioProcessor::getNumParameters()
{
    return totalNumParams;
}

float TaquitoAudioProcessor::getParameter (int index)
{
  switch(index){
  case breathParam:     return breath;
  case positionParam:   return position;
  case pressureParam:   return pressure;
  default:              return 0.0f;
  }
}

void TaquitoAudioProcessor::setParameter (int index, float value)
{
  switch(index){
  case breathParam:     breath = value; break;
  case positionParam:   position = value; break;
  case pressureParam:   pressure = value; break;
  default:              break;
  }
}

const String TaquitoAudioProcessor::getParameterName (int index)
{
  switch(index){
  case breathParam:     return "breath";
  case positionParam:   return "position";
  case pressureParam:   return "pressure";
  default:            return String::empty;
  }

}

const String TaquitoAudioProcessor::getParameterText (int index)
{
    return String(getParameter(index), 2);
}

const String TaquitoAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String TaquitoAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool TaquitoAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool TaquitoAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool TaquitoAudioProcessor::acceptsMidi() const
{
#if JucePlugin_WantsMidiInput
    return true;
#else
    return false;
#endif
}

bool TaquitoAudioProcessor::producesMidi() const
{
#if JucePlugin_ProducesMidiOutput
    return true;
#else
    return false;
#endif
}

int TaquitoAudioProcessor::getNumPrograms()
{
    return 0;
}

int TaquitoAudioProcessor::getCurrentProgram()
{
    return 0;
}

void TaquitoAudioProcessor::setCurrentProgram (int index)
{
}

const String TaquitoAudioProcessor::getProgramName (int index)
{
    return String::empty;
}

void TaquitoAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void TaquitoAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
  try{
    taquito.connect();
//   }catch(std::exception exc){
  }catch(...){
    // todo
  }
  keyboardState.reset();
  // initialisation that you need..
}

void TaquitoAudioProcessor::releaseResources()
{
  // When playback stops, you can use this as an opportunity to free up any
  taquito.disconnect();
  keyboardState.reset();
  // spare memory, etc.
}

void TaquitoAudioProcessor::updateController(int cid, int value, MidiBuffer& midiMessages){
  if(cid & 0x7f == 0 && ccvalues[cid] != value){
    midiMessages.addEvent(MidiMessage::controllerEvent(channel, cid, value), 0);
    ccvalues[cid] = value;
  }
}

void TaquitoAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    const int numSamples = buffer.getNumSamples();
//     for (int channel = 0; channel < getNumInputChannels(); ++channel)
//     {
//         float* channelData = buffer.getSampleData (channel);
//     }

  if(taquito.getBreath() > breathThreshold){
    if(taquito.getPressure() > pressureThreshold){
      float width = 1.0/25.0;
      float value = taquito.getPosition();
      if(value > width)
	value -= width/4;
      else
	value = 0.0;
      int8_t note = (int8_t)(value/width) + octave*12;
      if(note == lastnote - 1 && (value/width+octave*12-note) < width/2)
	note = lastnote;
      //       lastnote = taquito.getPosition()*25 + octave*12;
      if(note != lastnote){
	midiMessages.addEvent(MidiMessage::noteOn(channel, note, taquito.getBreath()*127), 1);
	midiMessages.addEvent(MidiMessage::noteOff(channel, lastnote), 0);
	lastnote = note;
      }
    }
  }else if(lastnote != -1){
    midiMessages.addEvent(MidiMessage::noteOff(channel, lastnote), 0);
    lastnote = -1;
  }

  updateController(pressureController, taquito.getPressure()*127, midiMessages);
  updateController(breathController, taquito.getBreath()*127, midiMessages);
  updateController(positionController, taquito.getPosition()*127, midiMessages);

  keyboardState.processNextMidiBuffer (midiMessages, 0, numSamples, true);

    // In case we have more outputs than inputs, we'll clear any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
    {
        buffer.clear (i, 0, buffer.getNumSamples());
    }
}

void TaquitoAudioProcessor::timerCallback()
{
  taquito.read();
  if(breath != taquito.getBreath())
    setParameterNotifyingHost(TaquitoAudioProcessor::breathParam, taquito.getBreath());
  if(position != taquito.getPosition())
    setParameterNotifyingHost(TaquitoAudioProcessor::positionParam, taquito.getPosition());
  if(pressure != taquito.getPressure())
    setParameterNotifyingHost(TaquitoAudioProcessor::pressureParam, taquito.getPressure());
}

//==============================================================================
bool TaquitoAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* TaquitoAudioProcessor::createEditor()
{
    return new TaquitoAudioProcessorEditor (this);
}

//==============================================================================
void TaquitoAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void TaquitoAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new TaquitoAudioProcessor();
}
