/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_BBC0EF66__
#define __PLUGINEDITOR_H_BBC0EF66__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class TaquitoAudioProcessorEditor  : public AudioProcessorEditor,
				     public SliderListener,
				     public Timer
{
public:
    TaquitoAudioProcessorEditor (TaquitoAudioProcessor* ownerFilter);
    ~TaquitoAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void resized();
    void sliderValueChanged (Slider*);
    void timerCallback();

private:
  MidiKeyboardComponent midiKeyboard;
  Label infoLabel, breathLabel, positionLabel, pressureLabel;
  Slider breathSlider;
  Slider positionSlider;
  Slider pressureSlider;
  ScopedPointer<ResizableCornerComponent> resizer;
  ComponentBoundsConstrainer resizeLimits;

  TaquitoAudioProcessor* getProcessor() const {
    return static_cast <TaquitoAudioProcessor*> (getAudioProcessor());
  }

};


#endif  // __PLUGINEDITOR_H_BBC0EF66__
