# Library path
LIBROOT=$(TEMPLATEROOT)/Drivers/

# Build path
BUILD=$(TEMPLATEROOT)/Build

# Code Paths
DEVICE=$(LIBROOT)/CMSIS/Device/ST/STM32F7xx
CMSIS=$(LIBROOT)/CMSIS/Include
PERIPH_FILE=$(LIBROOT)/STM32F7xx_StdPeriph_Driver
DSPLIB=$(LIBROOT)/CMSIS/DSP_Lib/Source
USB_DEVICE_FILE=$(TEMPLATEROOT)/Middlewares/ST/STM32_USB_Device_Library
#$(LIBROOT)/STM32_USB_Device_Library
USB_HOST_FILE=$(TEMPLATEROOT)/Middlewares/ST/STM32_USB_Host_Library
USB_OTG_FILE=$(LIBROOT)/STM32_USB_OTG_Driver
DRIVERS=$(LIBROOT)/STM32F7xx_HAL_Driver
FREERTOS_DIR=$(TEMPLATEROOT)/Middlewares/Third_Party/FreeRTOS/Source

# Compilation Flags
ARCH_FLAGS = -mcpu=cortex-m7 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16
ARCH_FLAGS += -fsingle-precision-constant
# DEF_FLAGS = -DUSE_STDPERIPH_DRIVER -DARM_MATH_CM4 -D__FPU_PRESENT -D__FPU_USED=1
DEF_FLAGS = -DSTM32F745xx -DARM_MATH_CM7 -D__FPU_PRESENT
# DEF_FLAGS = -DSTM32F745VG
INC_FLAGS = -I$(TEMPLATEROOT)/Libraries
INC_FLAGS += -I$(TEMPLATEROOT)/Source -I$(TEMPLATEROOT)/Inc -I$(TEMPLATEROOT)/MDK-ARM
INC_FLAGS += -I$(DEVICE)/Include -I$(CMSIS)
INC_FLAGS += -I$(DRIVERS)/Inc
INC_FLAGS += -I$(USB_HOST_FILE)/Core/Inc
INC_FLAGS += -I$(USB_DEVICE_FILE)/Core/Inc
INC_FLAGS += -I$(USB_HOST_FILE)/Class/CDC/Inc -I$(USB_HOST_FILE)/Class/AUDIO/Inc
INC_FLAGS += -I$(USB_DEVICE_FILE)/Class/CDC/Inc -I$(USB_DEVICE_FILE)/Class/AUDIO/Inc
INC_FLAGS += -I$(USB_OTG_FILE)/inc
INC_FLAGS += -I$(FREERTOS_DIR)/include
INC_FLAGS += -I$(FREERTOS_DIR)/portable/GCC/ARM_CM7/r0p1
INC_FLAGS += -I$(FREERTOS_DIR)/CMSIS_RTOS
CFLAGS += $(ARCH_FLAGS) $(INC_FLAGS) $(DEF_FLAGS)
CXXFLAGS += $(ARCH_FLAGS) $(INC_FLAGS) $(DEF_FLAGS)
LDFLAGS += -T$(LDSCRIPT) $(ARCH_FLAGS)

include $(TEMPLATEROOT)/common.mk
