#include "io.h"

 uint8_t TCCR0A, TCCR0B, TIMSK0;
 uint8_t EICRA, EIMSK;
 uint8_t ADCSRA, ADMUX;
 uint8_t ADCL, ADCH;
uint8_t TIMSK1, TCCR1A, TCCR1B, OCR1A, OCR1B;
uint8_t TIMSK2, TCCR2A, TCCR2B, OCR2A, OCR2B;
uint8_t UBRR0H, UBRR0L, UCSR0B, UCSR0A, UDR0;

uint8_t DDRB, DDRC, DDRD;
/* uint8_t PINB, PINC, PIND; */
uint8_t PORTB, PORTC, PORTD;

uint8_t SREG;
